# List of the API and terir request 

### fetch all ticket api call
GET http://localhost:8000/api/v1/

### add new ticket
POST http://localhost:8000/api/v1/
Content-Type: application/json

{
     "task": "newdata1",
    "hr" :545,
    "todo": false,
}

### update ticket
PATCH http://localhost:8000/api/v1/
Content-Type: application/json

{
    "id":"61296d8bf9754b15c2814604",
    "todo":"false"
}





### delete ticket

DELETE http://localhost:8000/api/v1/
Content-Type: application/json

{
   "id" : ["6128a59a400a746a48f214a5" ,"6128a756e2f89f4b9ec59813","6128a761e2f89f4b9ec59815"]
}